// Package apimodel provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package apimodel

// Defines values for WidgetColor.
const (
	WidgetColorBlue WidgetColor = "blue"
	WidgetColorRed  WidgetColor = "red"
)

// Defines values for WidgetUpdateColor.
const (
	WidgetUpdateColorBlue WidgetUpdateColor = "blue"
	WidgetUpdateColorRed  WidgetUpdateColor = "red"
)

// AnalyzeResult defines model for AnalyzeResult.
type AnalyzeResult struct {
	Analysis string `json:"analysis"`
	Id       string `json:"id"`
}

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// Widget defines model for Widget.
type Widget struct {
	Color  WidgetColor `json:"color"`
	Id     string      `json:"id"`
	Weight int32       `json:"weight"`
}

// WidgetColor defines model for Widget.Color.
type WidgetColor string

// WidgetList defines model for WidgetList.
type WidgetList struct {
	Items []Widget `json:"items"`
}

// WidgetUpdate defines model for WidgetUpdate.
type WidgetUpdate struct {
	Color  *WidgetUpdateColor `json:"color,omitempty"`
	Id     *string            `json:"id,omitempty"`
	Weight *int32             `json:"weight,omitempty"`
}

// WidgetUpdateColor defines model for WidgetUpdate.Color.
type WidgetUpdateColor string

// WidgetsCreateJSONRequestBody defines body for WidgetsCreate for application/json ContentType.
type WidgetsCreateJSONRequestBody = Widget

// WidgetsUpdateJSONRequestBody defines body for WidgetsUpdate for application/json ContentType.
type WidgetsUpdateJSONRequestBody = WidgetUpdate
